### ISSUE TITLE
On mac m1, unable to connect to postgres database

### ISSUE THREAD

**Issue by kvconvr** [bitnami/bitnami-docker-postgresql#302]
**Description**

I'm working on a MAC laptop with macOS 11.5.1 and Apple M1 chip. My docker version is 4.0.1 and I'm using the docker desktop version called MAC with Apple chip. 

I'm trying to use this bitnami postgres container as a database for Bitnami Apache Airflow configuration. I used the docker-compose.yml file from this location: https://github.com/bitnami/bitnami-docker-airflow. 

The postgres container comes up but Airflow component aren't able to connect to the posgres database. After a few minutes, the Airflow schedules dies due to timeout.  Log file snippets from docker container logs for postgres and Airflow scheduler provided below.

**Steps to reproduce the issue:**

1. Per the steps in https://github.com/bitnami/bitnami-docker-airflow, copy the docker-compose.yml into your directory using the curl command: curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-airflow/master/docker-compose.yml
2. Run the following command: docker-compose up -d

**Describe the results you received:**
Apache Airflow worker, scheduler components run but are not able to connect to the postgres database. The Airflow scheduler waits to connect to the postgres database; it times out and dies. The Airflow Admin console does not come up. 

Here's a snippet from the docker log for the postgres container:
postgresql 20:51:05.09 INFO  ==> ** Starting PostgreSQL **
2021-09-24 20:51:05.196 GMT [1] LOG:  pgaudit extension initialized
2021-09-24 20:51:05.201 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-09-24 20:51:05.202 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-09-24 20:51:05.204 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-24 20:51:05.244 GMT [239] LOG:  database system was shut down at 2021-09-24 20:50:41 GMT
2021-09-24 20:51:05.261 GMT [1] LOG:  database system is ready to accept connections
2021-09-24 20:51:07.380 GMT [253] LOG:  incomplete startup packet
2021-09-24 20:51:07.474 GMT [255] LOG:  incomplete startup packet
2021-09-24 20:51:07.480 GMT [257] LOG:  incomplete startup packet
2021-09-24 20:54:46.793 GMT [345] PANIC:  stuck spinlock detected at LWLockWaitListLock, lwlock.c:822
2021-09-24 20:54:46.793 GMT [345] STATEMENT:  SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.concurrency AS dag_concurrency, dag.max_active_runs AS dag_max_active_runs, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_create_after AS dag_next_dagrun_create_after, dag_tag_1.name AS dag_tag_1_name, dag_tag_1.dag_id AS dag_tag_1_dag_id 
	FROM dag LEFT OUTER JOIN dag_tag AS dag_tag_1 ON dag.dag_id = dag_tag_1.dag_id 
	WHERE dag.dag_id IN ('example_short_circuit_operator') FOR UPDATE OF dag
qemu: uncaught target signal 6 (Aborted) - core dumped
2021-09-24 20:54:46.828 GMT [1] LOG:  server process (PID 345) was terminated by signal 6: Aborted

From the airflow scheduler docker container log file:
Process ForkProcess-1:
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 370, in _run_processor_manager
    processor_manager.start()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 610, in start
    return self._run_parsing_loop()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 671, in _run_parsing_loop
    self._collect_results_from_processor(processor)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 981, in _collect_results_from_processor
    if processor.result is not None:
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 321, in result
    if not self.done:
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 286, in done
    if self._parent_channel.poll():
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/opt/bitnami/python/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
[2021-09-24 21:06:56,989] {manager.py:401} WARNING - DagFileProcessorManager (PID=266) exited with exit code 1 - re-launching
[2021-09-24 21:06:56,992] {manager.py:254} INFO - Launched DagFileProcessorManager with pid: 334
[2021-09-24 21:06:57,005] {settings.py:51} INFO - Configured default timezone Timezone('UTC')
[2021-09-24 21:07:47,857] {manager.py:414} ERROR - DagFileProcessorManager (PID=334) last sent a heartbeat 50.87 seconds ago! Restarting it
[2021-09-24 21:07:47,861] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 334
[2021-09-24 21:08:07,950] {process_utils.py:66} INFO - Process psutil.Process(pid=334, status='terminated', exitcode=0, started='21:06:56') (334) terminated with exit code 0
[2021-09-24 21:08:07,956] {manager.py:254} INFO - Launched DagFileProcessorManager with pid: 336
[2021-09-24 21:08:07,976] {settings.py:51} INFO - Configured default timezone Timezone('UTC')

**Describe the results you expected:**
I expected all the Apache Airflow components to come up and run, I should be able to log into the Airflow Admin console on localhost:8080.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to connect to the postgres database in the docker container via psql. I ran the following commands: 
psql -h 0.0.0.0 -p 5432 -U postgres and psql -h 127.0.0.1 -p 5432 -U postgres. I got the following results:
psql: error: could not connect to server: Connection refused
	Is the server running on host "0.0.0.0" and accepting
	TCP/IP connections on port 5432?

psql: error: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

**Version**

- Output of `docker version`: 
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:34 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Output of `docker info`:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 7
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: 2OIW:YVGQ:F365:B3RV:4FRT:3SOF:2XBB:XOPI:YFL3:VCWO:ZD4O:M4F2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

- Output of `docker-compose version` (if applicable):
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @kvconvr, I can see this error in the logs, from which it seems like there has been a qemu emulation error:

```
 qemu: uncaught target signal 6 (Aborted) - core dumped
```

Note that we don't provide ARM container images yet, so running containers on M1 requires relying on emulation, which in some cases will simply not work. You can read more about ARM support for Bitnami here: https://github.com/bitnami/charts/issues/7305

**Comment by demisx** [comment]
Indeed, using the official image from Postgres docker did the job. This is how we did it in [skaffold](https://skaffold.dev/) under helm chart deployment:

```yaml
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
  remoteChart: postgresql
  version: 10.13.4
  overrides:
    postgresqlPassword: 'postgres'
    persistence:
      enabled: false
    image:
      repository: postgres
      tag: '11'
    postgresqlDataDir: /tmp/data/pgdata
    persistence.mountPath: /tmp/data/
```
